spring:
  application:
    name: "%APP_NAME%"
    version: "%APP_VERSION%"
    build:
      time: "%APP_BUILD_TIME%"
      os:
        name: "%APP_BUILD_OS_NAME%"
        version: "%APP_BUILD_OS_VERSION%"
  profiles:
    active: development

management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always
      access: read_only
    info:
      access: read_only

---
###############################
### Development environment ###
###############################
spring:
  config:
    activate:
      on-profile: development

---
##########################
### Docker environment ###
##########################
spring:
  config:
    activate:
      on-profile: docker

---
##############################
### Kubernetes environment ###
##############################
spring:
  config:
    activate:
      on-profile: kubernetes
