spring:
  application:
    name: hlaeja-service
  profiles:
    active: development

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true

---
###############################
### Development environment ###
###############################
spring:
  config:
    activate:
      on-profile: development

---
##########################
### Docker environment ###
##########################
spring:
  config:
    activate:
      on-profile: docker

---
##############################
### Production environment ###
##############################
spring:
  config:
    activate:
      on-profile: production
